Kotlin homework
stukenvitalii/T-Fintech-Course_Kotlin pull request #1
Opened 2024-09-16 10:19 UTC by stukenvitalii

2024-09-16 10:24 UTC, stukenvitalii commented
Накосячил немного) пушил сразу в master😵‍💫 так что не удивляйся в какую ветку pr😂

2024-09-21 15:06 UTC, SHvatov requested changes
@stukenvitalii оставил пару комментариев, посмотри их, пожалуйста.

2024-09-21 15:06 UTC, SHvatov commented on src/main/kotlin/client/KudaGoClient.kt
> +    val logger = LoggerFactory.getLogger("KudaGoClient")
Я логгер держу в `companion object`'е, ибо и так под капотом это закэшированный синглтон)

2024-09-21 15:06 UTC, SHvatov commented on src/main/kotlin/client/KudaGoClient.kt
> +    private val baseUrlNews =
Аналогично, стоит вынести в виде константы в companion)

2024-09-21 15:06 UTC, SHvatov commented on src/main/kotlin/client/KudaGoClient.kt
> +        val response: List<News> = KudaGoClient().getNews(pageSize, page)
На каждый запрос по клиенту создавать очень расточительно)

Давай унесем этот метод в класс `KudaGoClient`

2024-09-21 15:06 UTC, SHvatov commented on src/main/kotlin/client/KudaGoClient.kt
> +    while (true) {
Такие потенциально бесконечные циклы стоит ограничивать. Можно было бы итерирование по страницам заменить на for, ограниченный сверху к примеру `Int.MAX_VALUE/2`. `pageSize` тоже стоит унести в константы, или вообще не передавать, он же у тебя равен значению аргумента по умолчанию.

2024-09-21 15:06 UTC, SHvatov commented on src/main/kotlin/client/KudaGoClient.kt
> +        if (filteredNews.size < pageSize) break
Вот это условие мне не совсем понятно) Если мы не нашли на странице новостей за промежуток времени, мы стопаримся. Сортировке по дате публикации в самом запросе я не вижу, то есть новости идут в каком-то своем внутреннем порядке. И если вдруг, на странице будет новость, не входящая в интересующий нас промежуток, то мы закончим исполнение. Так ведь? Попробуй в качестве даты окончания промежутка поставить вчерашний день, и твоя программа прервется на первой сегодняшней новости)

2024-09-21 15:06 UTC, SHvatov commented on src/main/kotlin/client/KudaGoClient.kt
> +fun saveNews(path: String, news: Collection<News>) {
Немного не в тему этот метод здесь, его бы унести еще куда-то.

2024-09-21 15:06 UTC, SHvatov commented on src/main/kotlin/Main.kt
> +    val readmeContent = readme {
👍 за DSL, получился хорошо)

2024-09-22 19:45 UTC, stukenvitalii commented
Вроде все поправил) @SHvatov

2024-09-26 17:24 UTC, merged

2024-09-29 18:50 UTC, SHvatov reviewed
@stukenvitalii 🔥, но, пожалуйста, не мерджи пока я не аппрувну)

2024-09-29 19:39 UTC, stukenvitalii commented
да, закрывал все открытые pr и случайно этот тоже закрыл))